
configfile: "workflow/config/example_config.yaml"

include: "rules/general.smk"
include: "rules/grids.smk"
include: "rules/pseudotrajectories.smk"
include: "rules/gromacs.smk"

from workflow.helpers.PATHS import PATH_OUTPUT, NAME_PT_FOLDER, NAME_NETWORK_FOLDER, NAME_ENERGY_FOLDER

MOLECULE_NAMES = f"{config['pseudotrajectory']['molecule_1']}_{config['pseudotrajectory']['molecule_2']}"
NETWORK_NAME = f"{config['grid']['unique_network_name']}"

EXPERIMENT_FULL_PATH = f"{PATH_OUTPUT}{MOLECULE_NAMES}/{NETWORK_NAME}/"

rule all:
    input:
        f"{EXPERIMENT_FULL_PATH}{NAME_ENERGY_FOLDER}energy.xvg",
        f"{EXPERIMENT_FULL_PATH}{NAME_PT_FOLDER}structure.gro",
        f"{EXPERIMENT_FULL_PATH}{NAME_NETWORK_FOLDER}grid.npy",
        f"{EXPERIMENT_FULL_PATH}config_used.yaml",
