configfile: "workflow/config/benzene_20_7_7_4_config.yaml"

wildcard_constraints:
    path = "<simulation>|<pseudosimulation>|<outputs_assignment>",
    N_xyz=r"\d+"

from workflow.helpers.build_subgrids import auto_create_grid

config = auto_create_grid(config)

pathvars:
    # general terms, not complete paths
    molecule1 = config["pseudotrajectory"]["molecule_1"],
    molecule2 = config["pseudotrajectory"]["molecule_2"],
    molecules = f"<molecule1>_<molecule2>/",
    network = f"{config['grid']['unique_network_name']}/",
    output_directory = "nobackup/",
    ext_str = config["pseudotrajectory"]["structure_ending"],
    ext_trj = config["pseudotrajectory"]["trajectory_ending"],

    # inputs
    inputs = "inputs/",
    inputs_gromacs =f"<inputs>default_gromacs/<molecules>",
    inputs_vmd =f"<inputs>vmd_scripts/<molecules>",
    inputs_structures = f"<inputs>one_molecule_structures/",

    #outputs
    output_specific_molecule = f"<output_directory><molecules>",
    output_specific_molecule_network = f"<output_specific_molecule><network>",

    # network
    outputs_network = "<output_specific_molecule_network>network/",

    # output simulation
    simulation = f"<output_specific_molecule>SIMULATION/",
    simulation_traj_slices = f"<simulation>trajectory_slices/",
    analysis_simulation = f"<output_specific_molecule_network>simulation/",

    # output related to specific grid
    pseudosimulation = f"<output_specific_molecule_network>pseudosimulation/",
    pseudosimulation_traj_slices = f"<pseudosimulation>trajectory_slices/",
    outputs_indices = f"<output_specific_molecule_network>important_indices/",
    outputs_assignment = f"<output_specific_molecule_network>assignment/",
    outputs_molecular_plots = f"<output_specific_molecule_network>molecular_plots/",
    outputs_other_plots = f"<output_specific_molecule_network>other_plots/",
    outputs_vmd = f"<output_specific_molecule_network>vmd/",
    outputs_transitions = f"<output_specific_molecule_network>transitions/",



include: "rules/general.smk"
include: "rules/grids.smk"
include: "rules/pseudosimulation.smk"
include: "rules/gromacs.smk"
include: "rules/indices.smk"
include: "rules/assign.smk"
include: "rules/plots.smk"
include: "rules/msm.smk"
include: "rules/sqra.smk"
include: "rules/graphene_xylene_specific.smk"
include: "rules/molecular_visualizations.smk"
include: "rules/print_info.smk"
include: "rules/orca.smk"


N=[1, 5, 20, 50]
N_xyz =[10]
view_index=config["analysis"]["view_index"]
zoom_level = config["analysis"]["zoom_level"]


def all_inputs(wildcards):
    frames = get_frames(wildcards)

    return [
        f"{GRID_DIR}/trajectory.xyz",
        f"{LOCAL_TEST_DIR}/trajectory.xyz",
        f"{LOCAL_TEST_DIR}/cleaned_trajectory.xyz",
        f"{LOCAL_TEST_DIR}/split_done.txt",
        f"{LOCAL_TEST_DIR}/copied_to_curta.txt"
        ] + \
        expand(
            f"{LOCAL_TEST_DIR}/{{frame}}/structure.xyz",
            frame=frames
        ) + \
        expand(
            f"{LOCAL_TEST_DIR}/{{frame}}/structure.inp",
            frame=frames
        )

rule all:
    input:
        "<output_specific_molecule_network>config_used.yaml",
        # grids
        "<outputs_network>grid_info.yaml",
        "<outputs_network>grid.npy",
        # pseudotrajectory
        "<pseudosimulation>structure.gro",
        "<pseudosimulation>trajectory.xtc",
        # #expand("<pseudosimulation>trajectory_slices/frame_{i}.gro", i=[8550891, 9472648, 8584358, 9641038, 11979713]),
        # "<pseudosimulation>energy.csv",
        # all_inputs,
        #f"{LOCAL_TEST_DIR}/curta_started.txt",
        # # lambda wc: expand(
        #     f"{BASE}/{{frame}}/structure.out",
        #     frame=get_frames(wc)
        # ),
        f"{LOCAL_TEST_DIR}/output.csv",
	    f"{LOCAL_TEST_DIR}/energy.csv",
	    f"{GRID_DIR}/energy.csv",
        f"{LOCAL_TEST_DIR}/times.txt",
        f"{LOCAL_TEST_DIR}/energy_vs_distance_100_lowest_highlighted.png",
        # expand(f"{GRID_DIR}/lowest_{{N_xyz}}_structures/", N_xyz=N_xyz),
        # expand(f"{LOCAL_TEST_DIR}/copied_low_E_to_curta_{{N_xyz}}.txt", N_xyz=N_xyz),
        # # expand(f"<outputs_frame_plots>{{sim_pseudo_wrapped}}/frame_{{frame_index}}_zoom{{zoom_level}}_view{{view_index}}.png",
        # # sim_pseudo_wrapped=["pseudosimulation"], frame_index=list(range(200)),
        # # zoom_level=[0], view_index=[1]),
        # # post-processing real simulation
        # # "<simulation>trajectory.<ext_trj>",
        # # # energy along trajectory and pseudotrajectory
        # # "<simulation>energy.csv",
        # # # find interesting indices
        # # expand("<outputs_indices>{traj_or_pseudo}_lowest_{N}_binding_energies.txt",
        # #     traj_or_pseudo=["simulation", "pseudosimulation"], N=[1, 5, 10, 50]),
        expand(f"<outputs_molecular_plots>lowest_energy/{{sim_pseudo_wrapped}}/{{N}}_lowest_zoom{{zoom_level}}_view{{view_index}}.png",
	        sim_pseudo_wrapped=["pseudosimulation"],
	        zoom_level=zoom_level, view_index=view_index, N=[1, 5, 20]),
        # "<outputs_indices>all_positions_first_rotation.txt",
        # "<outputs_indices>all_rotations_first_position.txt",
       # expand(f"<outputs_molecular_plots>all_translations/zoom{{zoom_level}}_view{{view_index}}_{{COM_or_full}}.png",
	   #  zoom_level=[8], view_index=[1], COM_or_full = ["COM", "full"]),
       # expand(f"<outputs_molecular_plots>all_rotations/zoom{{zoom_level}}_view{{view_index}}_{{COM_or_full}}.png",
       #     zoom_level=[8], view_index=[1], COM_or_full =["COM", "full"]),
        # # wrap and assign the trajectory
        # "<outputs_assignment>wrapped_trajectory.<ext_trj>",
        # "<outputs_assignment>full_assignment.npy",
        # expand(f"<outputs_molecular_plots>compare_to_assignment/overlapping_frame_{{i}}zoom{{zoom_level}}_view{{view_index}}_{{COM_or_full}}.png",
        #     zoom_level=[8],view_index=[1],COM_or_full=["COM", "full"], i=[5390, 44854, 83546, 27, 3567]),
        # #"<outputs_other_plots>hist_full_assignment.png",
        # # msm
        # expand(f"<outputs_transitions>{{tau}}/msm.npz", tau=[1, 5, 10, 20]),
        # "<outputs_other_plots>its.png",
        # rules.get_all_eigenvectors.input,
        # rules.plot_all_eigenvectors_as_lines.input,
        # expand(
        # f"<outputs_molecular_plots>eigenvectors/{{tau}}/ALL_EIGENVECTORS_zoom{{zoom_level}}_view{{view_index}}_{{COM_or_full}}.png",
        # zoom_level=zoom_level, view_index=view_index, COM_or_full=["full"], tau=[1, 10, 100]),
        # # sqra
        # "<outputs_transitions>sqra/reduced_sqra.npz",
        # "<outputs_transitions>sqra/eigenvectors.npy",
        # rules.plot_sqra_eigenvectors_as_lines.output,
        # rules.plot_sqra_eigenvalues.output,
        # rules.get_eigenvectors_sum_1.input,
        # rules.get_eigenvectors_sum_0.input,
        # rules.get_eigenvectors_sum_other.input
        # expand(f"<outputs_molecular_plots>eigenvectors/sqra/stacked_{{color}}_{{i}}th_eigenvector_zoom{{zoom_level}}_view{{view_index}}_{{COM_or_full}}.png",
        # zoom_level=zoom_level, view_index=view_index, COM_or_full=["full"], i=[1,2,3], color=["red", "blue"]),
        #f"<outputs_other_plots>array_sqra.png",

        # "<outputs_other_plots>grouped_by_zcoo_eigenvectors_for_tau_sqra.png",
        # "<outputs_other_plots>grouped_by_trans_eigenvectors_for_tau_sqra.png",
        # "<outputs_other_plots>grouped_by_rotation_eigenvectors_for_tau_sqra.png"
        # #
        # # # specific plots for the system
        # #expand("<outputs_other_plots>{which}/ring_vector.png", which=["simulation", "pseudosimulation"]),
        # expand("<outputs_other_plots>{which}/ring_position_lowest_{N}.png", N=[1, 3, 10, 100, 250, 500], which=["simulation", "pseudosimulation"]),



