unique_network_name: "graphene_grid_D1"

rotation_algorithm: "hypercube"
rotation_random_seed: 1
N_rotations:  1
translation_algorithm: "cartesian_xy_periodic"
translation_subgrids_A: [[-2, 2, 6], [-2, 2, 6], [10, 14, 5]]



