grid:
  unique_network_name: "positions_200rot"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 200
  translation_algorithm: "cartesian"
  periodic_in: [False, False, False]
  translation_subgrids_A: [ [-3, 3, 10], [ -3, 3, 10], [1, 10, 20] ]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "benzene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

analysis:
  energy_program: GROMACS
  zoom_level: [ 0 ]
  view_index: [ 1 ]
  length_shortened_trajectory_ns: 10
  energy_types: ["Potential"]
  upper_E_limit: 0
  analyse_first_N_frames: None

msm:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 8
  num_extremes_to_plot: "auto"
  capping_factor: None
  cutting_factor: 500
  tolerance: 1e-15
  sigma_sqra: 1e-15
  taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 300, 500, 1000]