grid:
  unique_network_name: cart_10_3_3_3
  rotation_algorithm: hypercube
  rotation_random_seed: 1
  N_rotations: 10
  translation_algorithm: cartesian
  periodic_in: [false, false, false]
  translation_subgrids_A: [[-4, 4, 3], [-4, 4, 3], [3, 5, 3]]
pseudotrajectory:
  molecule_1: benzene
  molecule_2: benzene
  structure_ending: gro
  trajectory_ending: xtc
analysis:
  energy_program: GROMACS
  length_shortened_trajectory_ns: 10
  energy_types: [LJ (SR), Coulomb (SR)]
  upper_E_limit: 0
  analyse_first_N_frames: None
  zoom_level: 0
  view_index: [1, 2]
msm:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: auto
  taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 300, 500, 1000]
eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: auto
sqra:
  capping_factor: None
  cutting_factor: auto
  tolerance_rate_matrix_row_sum: 1e-12
  tolerance_eigendecomposition: 0
  sigma: 0

