grid:
  unique_network_name: "positions_200rot"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 200
  translation_algorithm: "cartesian"
  periodic_in: [False, False, False]
  translation_subgrids_A: [ [-3, 3, 20], [ -3, 3, 20], [1, 10, 20] ]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "benzene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

analysis:
  energy_program: GROMACS
  view_index: [ 1 ]
  length_shortened_trajectory_ns: 10
  energy_types: ["Potential"]
  upper_E_limit: 0
  analyse_first_N_frames: None

sqra:
  cutting_factor: "auto"
  tolerance_rate_matrix_row_sum: 1e-12
  sigma: 1e-30
  tolerance_eigendecomposition: 1e-30

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: "auto"