grid:
  unique_network_name: "cart_20_7_7_4"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 20
  translation_algorithm: "cartesian"
  periodic_in: [False, False, False]
  translation_subgrids_A: [ [-6,6,7], [-6,6,7], [0, 6, 4] ]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "benzene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

analysis:
  energy_program: GROMACS
  length_shortened_trajectory_ns: 10
  energy_types: ["LJ (SR)", "Coulomb (SR)"]
  upper_E_limit: 0
  analyse_first_N_frames: None
  zoom_level: 0
  view_index: [ 1 , 2 , 4 , 5, 6,7]

energy:
  energy_program: GROMACS

plotting:
  upper_E_limit: 0

msm:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: 1
  taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 300, 500, 1000]
  tolerance: 0

sqra:
  # rate matrix reduction
  capping_factor: None
  cutting_factor: "auto"
  tolerance_rate_matrix_row_sum: 1e-8
  # eigendecomposition
  tolerance_eigendecomposition: 0
  sigma: 0

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: "auto"