grid:
  unique_network_name: "graphene_grid_C1"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 1
  translation_algorithm: "cartesian_xy_periodic"
  translation_subgrids_A: [ [ -3.07, 1.85, 6 ], [ -4.26, 4.26,10 ], [1, 14, 13 ] ]

pseudotrajectory:
  molecule_1: "graphene"
  molecule_2: "xylene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

energy:
  energy_program: GROMACS

plotting:
  plot_N_lowest: 10
