perform_simulation: False

grid:
  unique_network_name: "auto_grid_20"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 20
  translation_algorithm: "cartesian_xy_periodic"
  translation_subgrids_A: [ [None, None, 10], [ None, None, 10], [2, 5, 10] ]

pseudotrajectory:
  molecule_1: "graphene"
  molecule_2: "xylene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

energy:
  energy_program: GROMACS


plotting:
  upper_E_limit: 0
