grid:
  unique_network_name: "spherical"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 1
  periodic_in: [ False, False ]
  translation_algorithm: "spherical"
  translation_subgrids_A: [ 80, [3, 20, 20] ]

pseudotrajectory:
  molecule_1: "natrium"
  molecule_2: "chloride"
  structure_ending: "gro"
  trajectory_ending: "xtc"

analysis:
  energy_program: GROMACS
  zoom_level: [ 0 ]
  view_index: [ 1 ]
  length_shortened_trajectory_ns: 10
  upper_E_limit: 0
  energy_types: ["Potential"]
  analyse_first_N_frames: None

msm:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 8
  num_extremes_to_plot: "auto"
  taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 300, 500, 1000]