grid:
  unique_network_name: "simple_grid_A20"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 20
  translation_algorithm: "cartesian_xy_periodic"
  translation_subgrids_A: [ [ -1.53, 0.93, 5], [ 0, 4.26, 5], [2, 5, 5 ] ]

pseudotrajectory:
  molecule_1: "graphene"
  molecule_2: "xylene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

energy:
  energy_program: GROMACS

plotting:
  energy_type_name: Potential
  plot_N_lowest: 5
  upper_E_limit: 0
