perform_simulation: True

grid:
  unique_network_name: "spherical_grid_20"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 20
  periodic_in: [False, False]
  translation_algorithm: "spherical"
  translation_subgrids_A: [55, [2, 10, 5]]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "benzene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

energy:
  energy_program: GROMACS

plotting:
  upper_E_limit: 0

