PATH_OUTPUT = "nobackup/"
NAME_NETWORK_FOLDER = "full_network/"
NAME_PT_FOLDER = "pseudotrajectory/"
NAME_SIMULATION_FOLDER = "simulation/"
NAME_TEST_FOLDER = "test/"
NAME_ENERGY_FOLDER = "energy/"
NAME_LOWEST_E_FOLDER = "lowest_E_plots/"
NAME_VMD_OUTPUT = "molecular_vmd/"
NAME_FRAME_PLOTS = "frame_plots/"
NAME_PLOTS = "plots/"

PATH_INPUT_MOLECULES = "inputs/one_molecule_structures/"
PATH_INPUT_DEFAULT_GROMACS = "inputs/default_gromacs/"
PATH_VMD_SCRIPTS = "inputs/vmd_scripts/"